apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zynta-studio
  namespace: zynta-studio
spec:
  rules:
  - host: ide.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zynta-studio-service
            port:
              number: 80
