apiVersion: v1
kind: Service
metadata:
  name: zynta-studio-service
  namespace: zynta-studio
spec:
  selector:
    app: zynta-studio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
