apiVersion: v1
kind: Service
metadata:
  name: god-level-ide-service
  namespace: god-level-ide
spec:
  selector:
    app: god-level-ide
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
